version: "3.0"
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - elk
#----------------- 
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - elk      
#----------------- 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    depends_on:
      - kafka
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx512m -Xms256m
      ELASTIC_PASSWORD: 'changeme'
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      cluster.name: "docker-cluster"
      node.name: cluster-1
    volumes:
      #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
 #-----------------   
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    networks:
      - elk
#-----------------
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.11.0
    environment:
      LS_JAVA_OPTS: -Xmx256m -Xms256m
    depends_on:
      - kibana
    ports:
      - 5044:5044
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - 9600:9600
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    networks:
      - elk
#    volumes:
#      - type: bind
#        source: ./logstash_pipeline/
#        target: /usr/share/logstash/pipeline
#        read_only: true
#-----------------

networks:
  elk:
    driver: bridge

volumes: 
    elasticsearch: 